EduBlockchain: edu.UNO.blockChain.form.TokenMapper Class Reference
edu.UNO.blockChain.form.TokenMapper Class Reference
Public Member Functions
Tokenform mapRow (ResultSet rs, int rowNum) throws SQLException
Detailed Description
Author
fire-holder
Member Function Documentation
mapRow()
Tokenform edu.UNO.blockChain.form.TokenMapper.mapRow (ResultSet rs, int rowNum) throws SQLException
Parameters
rs
rowNum
Returns
Exceptions
SQLException
References edu.UNO.blockChain.form.Tokenform.setId(), edu.UNO.blockChain.form.Tokenform.setOwner(), and edu.UNO.blockChain.form.Tokenform.setToken().
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/form/TokenMapper.java