EduBlockchain: edu.UNO.blockChain.form.Broadcastform Class Reference
edu.UNO.blockChain.form.Broadcastform Class Reference
Public Member Functions
Broadcastform ()
Broadcastform (String receiver, int amount, String hashid)
String getReceiver ()
void setReceiver (String receiver)
int getAmount ()
void setAmount (int amount)
String getHashid ()
void setHashid (String hashid)
Detailed Description
The class for broadcast object.
Author
fire-holder
Constructor & Destructor Documentation
Broadcastform() [1/2]
edu.UNO.blockChain.form.Broadcastform.Broadcastform ()
Default constructor
Broadcastform() [2/2]
edu.UNO.blockChain.form.Broadcastform.Broadcastform (String receiver, int amount, String hashid)
Constructor to set the receiver, amount and hash id.
Parameters
receiver String of receiver
amount An int for amount
hashid String for hash id.
Member Function Documentation
getAmount()
int edu.UNO.blockChain.form.Broadcastform.getAmount ()
Get method for amount.
Returns
An int of amount
Referenced by edu.UNO.blockChain.repository.Broadcastrepo.createTransaction().
getHashid()
String edu.UNO.blockChain.form.Broadcastform.getHashid ()
Get method for hash id.
Returns
String of hash id.
Referenced by edu.UNO.blockChain.repository.Broadcastrepo.createTransaction().
getReceiver()
String edu.UNO.blockChain.form.Broadcastform.getReceiver ()
Get method for receiver.
Returns
String of receiver.
Referenced by edu.UNO.blockChain.repository.Broadcastrepo.createTransaction().
setAmount()
void edu.UNO.blockChain.form.Broadcastform.setAmount (int amount)
Set method for amount.
Parameters
amount The int to set the amount.
setHashid()
void edu.UNO.blockChain.form.Broadcastform.setHashid (String hashid)
Set method for hash id.
Parameters
hashid The string to set the hash id.
setReceiver()
void edu.UNO.blockChain.form.Broadcastform.setReceiver (String receiver)
Set method for receiver.
Parameters
receiver String of receiver
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/form/Broadcastform.java