EduBlockchain: edu.UNO.blockChain.repository.Broadcastrepo Class Reference
edu.UNO.blockChain.repository.Broadcastrepo Class Reference
Public Member Functions
int createTransaction (Broadcastform createForm, String user)
List< Tokenform > findByTokens (String user)
List< Pollform > findByPolls ()
String minereward (String miner)
Member Function Documentation
createTransaction()
int edu.UNO.blockChain.repository.Broadcastrepo.createTransaction (Broadcastform createForm, String user)
References edu.UNO.blockChain.form.Broadcastform.getAmount(), edu.UNO.blockChain.form.Broadcastform.getHashid(), and edu.UNO.blockChain.form.Broadcastform.getReceiver().
Referenced by edu.UNO.blockChain.controller.webController.createTX().
findByPolls()
List<Pollform> edu.UNO.blockChain.repository.Broadcastrepo.findByPolls ()
Referenced by edu.UNO.blockChain.controller.webController.txpoll().
findByTokens()
List<Tokenform> edu.UNO.blockChain.repository.Broadcastrepo.findByTokens (String user)
Referenced by edu.UNO.blockChain.controller.webController.broadcast(), and edu.UNO.blockChain.controller.webController.token().
minereward()
String edu.UNO.blockChain.repository.Broadcastrepo.minereward (String miner)
Referenced by edu.UNO.blockChain.controller.webController.miningpending().
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/repository/Broadcastrepo.java