EduBlockchain: edu.UNO.blockChain.controller.webController Class Reference
edu.UNO.blockChain.controller.webController Class Reference
Public Member Functions
String index ()
String home ()
String register ()
String login ()
String user ()
String hash ()
String block ()
ModelAndView animation ()
String login (UserForm sig)
String userInfo (UserForm reg)
String broadcast (Model model)
String createTX (Broadcastform tx)
String token (Model model)
String txpoll (Model model)
String miningpending ()
Detailed Description
This class is the web controller. Will try to use RestController in the future implementation
Author
Xingyu Chen
Member Function Documentation
animation()
ModelAndView edu.UNO.blockChain.controller.webController.animation ()
Get mapping and go to animation page.
Returns
modelandview to redirect the page.
block()
String edu.UNO.blockChain.controller.webController.block ()
Get mapping and go to the block page.
Returns
"block"
broadcast()
String edu.UNO.blockChain.controller.webController.broadcast (Model model)
Get mapping and create the transaction, then go to the transaction page.
Parameters
model the model to add attribute of tokenList.
Returns
"broadcast"
References edu.UNO.blockChain.repository.Broadcastrepo.findByTokens().
createTX()
String edu.UNO.blockChain.controller.webController.createTX (Broadcastform tx)
Post mapping and go to the user page after the transaction was created.
Parameters
tx the broadcast form used to create transcation.
Returns
"user"
References edu.UNO.blockChain.repository.Broadcastrepo.createTransaction().
hash()
String edu.UNO.blockChain.controller.webController.hash ()
Get mapping and go to the sha256 page.
Returns
"sha256"
home()
String edu.UNO.blockChain.controller.webController.home ()
Get mapping and go to the home page.
Returns
"home"
index()
String edu.UNO.blockChain.controller.webController.index ()
Get mapping and go to the home page.
Returns
"home"
login() [1/2]
String edu.UNO.blockChain.controller.webController.login ()
Get mapping and go to the login page.
Returns
"sign"
login() [2/2]
String edu.UNO.blockChain.controller.webController.login (UserForm sig)
Post mapping and go to the user page if signed in successfully. Remain in the sign in page if unsuccessful.
Parameters
sig user name that used to sign in.
Returns
"user" if successful, "sign" if unsuccessful.
References edu.UNO.blockChain.repository.UserRepository.signinUser().
miningpending()
String edu.UNO.blockChain.controller.webController.miningpending ()
Get mapping of "/mining" and go to the home page.
Returns
"home"
References edu.UNO.blockChain.repository.Broadcastrepo.minereward(), and edu.UNO.blockChain.repository.UserRepository.miningpending().
register()
String edu.UNO.blockChain.controller.webController.register ()
Get mapping and go to the register page.
Returns
"register"
token()
String edu.UNO.blockChain.controller.webController.token (Model model)
Get mapping and go to the token page.
Parameters
model The model used to add attribute tokenList1.
Returns
"token"
References edu.UNO.blockChain.repository.Broadcastrepo.findByTokens().
txpoll()
String edu.UNO.blockChain.controller.webController.txpoll (Model model)
Get mapping and go to the transaction poll.
Parameters
model The model used to add attribute poll list.
Returns
"transactionpoll"
References edu.UNO.blockChain.repository.Broadcastrepo.findByPolls().
user()
String edu.UNO.blockChain.controller.webController.user ()
Get mapping and go to the user page.
Returns
"user"
userInfo()
String edu.UNO.blockChain.controller.webController.userInfo (UserForm reg)
Post mapping and go to the home page if registered.
Parameters
reg user name that used to register
Returns
"home"
References edu.UNO.blockChain.repository.UserRepository.registerUser().
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/controller/webController.java