EduBlockchain: edu.UNO.blockChain.form.blockChainMapper Class Reference
edu.UNO.blockChain.form.blockChainMapper Class Reference
Public Member Functions
blockChainform mapRow (ResultSet rs, int rowNum) throws SQLException
Detailed Description
The class is the block chain mapper.
Author
fire-holder
Member Function Documentation
mapRow()
blockChainform edu.UNO.blockChain.form.blockChainMapper.mapRow (ResultSet rs, int rowNum) throws SQLException
To map a row of block chain.
Parameters
rs The result set.
rowNum The number of rows.
Returns
The block chain that have set each data value.
Exceptions
SQLException
References edu.UNO.blockChain.form.blockChainform.setAmount(), edu.UNO.blockChain.form.blockChainform.setBlockheader(), edu.UNO.blockChain.form.blockChainform.setDate(), edu.UNO.blockChain.form.blockChainform.setId(), edu.UNO.blockChain.form.blockChainform.setNonce(), edu.UNO.blockChain.form.blockChainform.setPreviousblock(), edu.UNO.blockChain.form.blockChainform.setReceiver(), edu.UNO.blockChain.form.blockChainform.setSender(), and edu.UNO.blockChain.form.blockChainform.setTimestamp().
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/form/blockChainMapper.java