EduBlockchain: edu.UNO.blockChain.form.blockChainform Class Reference
edu.UNO.blockChain.form.blockChainform Class Reference
Public Member Functions
blockChainform ()
blockChainform (int id, String blockheader, String nonce, String previousblock, String timestamp, String transaction, String sender, String receiver, int amount, String date)
String getBlockheader ()
void setBlockheader (String blockheader)
String getNonce ()
void setNonce (String nonce)
String getPreviousblock ()
void setPreviousblock (String previousblock)
String getTimestamp ()
void setTimestamp (String timestamp)
String getTransaction ()
void setTransaction (String transaction)
int getId ()
void setId (int id)
String getSender ()
void setSender (String sender)
String getReceiver ()
void setReceiver (String receiver)
int getAmount ()
void setAmount (int amount)
String getDate ()
void setDate (String date)
Detailed Description
The class for block chain object.
Author
fire-holder
Constructor & Destructor Documentation
blockChainform() [1/2]
edu.UNO.blockChain.form.blockChainform.blockChainform ()
Default constructor
blockChainform() [2/2]
edu.UNO.blockChain.form.blockChainform.blockChainform (int id, String blockheader, String nonce, String previousblock, String timestamp, String transaction, String sender, String receiver, int amount, String date)
Constructor to set id, block header, nonce, previous block, timestamp, transaction, sender receiver, amount and date.
Parameters
id An int of id.
blockheader A string of block header.
nonce A string of nonce.
previousblock A string of previous block.
timestamp A string of time stamp.
transaction A string of transaction.
sender A string of sender.
receiver A string of receiver.
amount An int of amount.
date A string of date.
Member Function Documentation
getAmount()
int edu.UNO.blockChain.form.blockChainform.getAmount ()
Get method for amount.
Returns
The int of amount.
getBlockheader()
String edu.UNO.blockChain.form.blockChainform.getBlockheader ()
Get method for block header.
Returns
String of block header.
getDate()
String edu.UNO.blockChain.form.blockChainform.getDate ()
Get method for date.
Returns
The string of date.
getId()
int edu.UNO.blockChain.form.blockChainform.getId ()
Get method for ID.
Returns
An int of ID.
getNonce()
String edu.UNO.blockChain.form.blockChainform.getNonce ()
Get method for nonce.
Returns
String of nonce.
getPreviousblock()
String edu.UNO.blockChain.form.blockChainform.getPreviousblock ()
Get method for previous block.
Returns
The string of previous block.
getReceiver()
String edu.UNO.blockChain.form.blockChainform.getReceiver ()
Get method for receiver.
Returns
The string of receiver.
getSender()
String edu.UNO.blockChain.form.blockChainform.getSender ()
Get method for sender.
Returns
The string of sender.
getTimestamp()
String edu.UNO.blockChain.form.blockChainform.getTimestamp ()
Get method for time stamp.
Returns
The string of time stamp.
getTransaction()
String edu.UNO.blockChain.form.blockChainform.getTransaction ()
Get method for transaction.
Returns
The string of transaction.
setAmount()
void edu.UNO.blockChain.form.blockChainform.setAmount (int amount)
Set method for amount.
Parameters
amount The int of amount.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setBlockheader()
void edu.UNO.blockChain.form.blockChainform.setBlockheader (String blockheader)
Set method for block header.
Parameters
blockheader The string of block header.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setDate()
void edu.UNO.blockChain.form.blockChainform.setDate (String date)
Set method for date.
Parameters
date The string of date.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setId()
void edu.UNO.blockChain.form.blockChainform.setId (int id)
Set method for ID.
Parameters
id The int of ID.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setNonce()
void edu.UNO.blockChain.form.blockChainform.setNonce (String nonce)
Set method for nonce.
Parameters
nonce The string of nonce.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setPreviousblock()
void edu.UNO.blockChain.form.blockChainform.setPreviousblock (String previousblock)
Set method for previous block.
Parameters
previousblock The string of previous block.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setReceiver()
void edu.UNO.blockChain.form.blockChainform.setReceiver (String receiver)
Set method for receiver.
Parameters
receiver The string of receiver.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setSender()
void edu.UNO.blockChain.form.blockChainform.setSender (String sender)
Set method for sender.
Parameters
sender The string of sender.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setTimestamp()
void edu.UNO.blockChain.form.blockChainform.setTimestamp (String timestamp)
Set method for time stamp.
Parameters
timestamp The string of time stamp.
Referenced by edu.UNO.blockChain.form.blockChainMapper.mapRow().
setTransaction()
void edu.UNO.blockChain.form.blockChainform.setTransaction (String transaction)
Set method for transaction.
Parameters
transaction The string of transaction.
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/form/blockChainform.java