EduBlockchain: edu.uno.blockchain.form.UserForm Class Reference
edu.uno.blockchain.form.UserForm Class Reference
Public Member Functions
UserForm ()
String getnuid ()
void setnuid (String unid)
String getPassword ()
void setPassword (String password)
Integer getWallet ()
void setWallet (Integer wallet)
String getAUTHORITY ()
void setAUTHORITY (String aUTHORITY)
String getPrivatekey ()
void setPrivatekey (String privatekey)
Constructor & Destructor Documentation
UserForm()
edu.uno.blockchain.form.UserForm.UserForm ()
Member Function Documentation
getAUTHORITY()
String edu.uno.blockchain.form.UserForm.getAUTHORITY ()
getnuid()
String edu.uno.blockchain.form.UserForm.getnuid ()
Referenced by edu.uno.blockchain.repository.UserRepository.registerUser(), and edu.uno.blockchain.repository.UserRepository.signinUser().
getPassword()
String edu.uno.blockchain.form.UserForm.getPassword ()
Referenced by edu.uno.blockchain.repository.UserRepository.registerUser(), and edu.uno.blockchain.repository.UserRepository.signinUser().
getPrivatekey()
String edu.uno.blockchain.form.UserForm.getPrivatekey ()
getWallet()
Integer edu.uno.blockchain.form.UserForm.getWallet ()
setAUTHORITY()
void edu.uno.blockchain.form.UserForm.setAUTHORITY (String aUTHORITY)
setnuid()
void edu.uno.blockchain.form.UserForm.setnuid (String unid)
setPassword()
void edu.uno.blockchain.form.UserForm.setPassword (String password)
setPrivatekey()
void edu.uno.blockchain.form.UserForm.setPrivatekey (String privatekey)
setWallet()
void edu.uno.blockchain.form.UserForm.setWallet (Integer wallet)
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/form/UserForm.java