EduBlockchain: edu.UNO.blockChain.form.PollMapper Class Reference
edu.UNO.blockChain.form.PollMapper Class Reference
Public Member Functions
Pollform mapRow (ResultSet rs, int rowNum) throws SQLException
Detailed Description
This class is the poll mapper.
Author
fire-holder
Member Function Documentation
mapRow()
Pollform edu.UNO.blockChain.form.PollMapper.mapRow (ResultSet rs, int rowNum) throws SQLException
To map a row of poll.
Parameters
rs The result set.
rowNum The number of rows.
Returns
The poll that have set each data value.
Exceptions
SQLException
References edu.UNO.blockChain.form.Pollform.setAmount(), edu.UNO.blockChain.form.Pollform.setDate(), edu.UNO.blockChain.form.Pollform.setFee(), edu.UNO.blockChain.form.Pollform.setHash(), edu.UNO.blockChain.form.Pollform.setId(), edu.UNO.blockChain.form.Pollform.setReceiver(), and edu.UNO.blockChain.form.Pollform.setSender().
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/form/PollMapper.java