EduBlockchain: edu.uno.blockchain.repository.UserRepository Class Reference
edu.uno.blockchain.repository.UserRepository Class Reference
Public Member Functions
int registerUser (UserForm user)
boolean signinUser (UserForm user)
List< String > gettransactionpoll ()
List< String > gettokentable ()
String miningpending ()
Member Function Documentation
gettokentable()
List<String> edu.uno.blockchain.repository.UserRepository.gettokentable ()
gettransactionpoll()
List<String> edu.uno.blockchain.repository.UserRepository.gettransactionpoll ()
Referenced by edu.uno.blockchain.controller.UserController.gettransactionpoll().
miningpending()
String edu.uno.blockchain.repository.UserRepository.miningpending ()
References edu.uno.blockchain.function.Block.blockheader, edu.uno.blockchain.function.Block.mineBlock(), edu.uno.blockchain.function.Block.nonce, and edu.uno.blockchain.function.Block.timeStamp.
Referenced by edu.uno.blockchain.controller.WebController.miningpending().
registerUser()
int edu.uno.blockchain.repository.UserRepository.registerUser (UserForm user)
References edu.uno.blockchain.form.UserForm.getnuid(), and edu.uno.blockchain.form.UserForm.getPassword().
Referenced by edu.uno.blockchain.controller.WebController.userInfo().
signinUser()
boolean edu.uno.blockchain.repository.UserRepository.signinUser (UserForm user)
References edu.uno.blockchain.form.UserForm.getnuid(), and edu.uno.blockchain.form.UserForm.getPassword().
Referenced by edu.uno.blockchain.controller.WebController.login().
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/repository/UserRepository.java