EduBlockchain: edu.UNO.blockChain.form.Pollform Class Reference
edu.UNO.blockChain.form.Pollform Class Reference
Public Member Functions
Pollform ()
int getId ()
void setId (int id)
int getAmount ()
void setAmount (int amount)
int getFee ()
void setFee (int fee)
String getHash ()
void setHash (String hash)
String getDate ()
void setDate (String date)
String getSender ()
void setSender (String sender)
String getReceiver ()
void setReceiver (String receiver)
Pollform (int id, int amount, int fee, String hash, String date, String sender, String receiver)
Detailed Description
Author
fire-holder
Constructor & Destructor Documentation
Pollform() [1/2]
edu.UNO.blockChain.form.Pollform.Pollform ()
Pollform() [2/2]
edu.UNO.blockChain.form.Pollform.Pollform (int id, int amount, int fee, String hash, String date, String sender, String receiver)
Parameters
id
amount
fee
hash
date
sender
receiver
Member Function Documentation
getAmount()
int edu.UNO.blockChain.form.Pollform.getAmount ()
Returns
getDate()
String edu.UNO.blockChain.form.Pollform.getDate ()
Returns
getFee()
int edu.UNO.blockChain.form.Pollform.getFee ()
Returns
getHash()
String edu.UNO.blockChain.form.Pollform.getHash ()
Returns
getId()
int edu.UNO.blockChain.form.Pollform.getId ()
Returns
getReceiver()
String edu.UNO.blockChain.form.Pollform.getReceiver ()
Returns
getSender()
String edu.UNO.blockChain.form.Pollform.getSender ()
Returns
setAmount()
void edu.UNO.blockChain.form.Pollform.setAmount (int amount)
Parameters
amount
Referenced by edu.UNO.blockChain.form.PollMapper.mapRow().
setDate()
void edu.UNO.blockChain.form.Pollform.setDate (String date)
Parameters
date
Referenced by edu.UNO.blockChain.form.PollMapper.mapRow().
setFee()
void edu.UNO.blockChain.form.Pollform.setFee (int fee)
Parameters
fee
Referenced by edu.UNO.blockChain.form.PollMapper.mapRow().
setHash()
void edu.UNO.blockChain.form.Pollform.setHash (String hash)
Parameters
hash
Referenced by edu.UNO.blockChain.form.PollMapper.mapRow().
setId()
void edu.UNO.blockChain.form.Pollform.setId (int id)
Parameters
id
Referenced by edu.UNO.blockChain.form.PollMapper.mapRow().
setReceiver()
void edu.UNO.blockChain.form.Pollform.setReceiver (String receiver)
Parameters
receiver
Referenced by edu.UNO.blockChain.form.PollMapper.mapRow().
setSender()
void edu.UNO.blockChain.form.Pollform.setSender (String sender)
Parameters
sender
Referenced by edu.UNO.blockChain.form.PollMapper.mapRow().
The documentation for this class was generated from the following file:
C:/Users/81916/Documents/GitHub/EduBlockchain/project/src/main/java/edu/UNO/blockChain/form/Pollform.java